server:
   port: 8888
info:
   name: 分布式
   contact: lianshou
   
spring: 
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: D:/config
   rabbitmq:
      host: 192.168.1.124
      port: 5672
      username: cxadmin
      password: cxadmin