spring: 
   application:
      name: config-server
   profiles:
      active: dev1
   cloud:
      config:
         server:           
            git: 
               uri: https://github.com/bigcamel/config-hub.git
               username: admin123
               password: admin123             
   rabbitmq:
      host: 192.168.1.124
      port: 5672
      username: admin
      password: admin